### ISSUE TITLE
Reproducibility and over-removal problem

### ISSUE THREAD

**Issue by Yosshi999** [cvg/nerf-on-the-go#5]
I ran the following training script: 

<details>
<summary>training scripts</summary>

```
python -m train \
  --gin_configs=configs/360_dino.gin \
  --gin_bindings="Config.data_dir='Datasets/on-the-go/mountain'" \
  --gin_bindings="Config.checkpoint_dir='output/mountain/run_1/checkpoints'" \
  --gin_bindings="Config.patch_size=32" \
  --gin_bindings="Config.dilate=4" \ 
  --gin_bindings="Config.data_loss_type='on-the-go'"
  
python -m train \
  --gin_configs=configs/360_dino.gin \
  --gin_bindings="Config.data_dir='Datasets/on-the-go/fountain'" \
  --gin_bindings="Config.checkpoint_dir='output/fountain/run_1/checkpoints'" \
  --gin_bindings="Config.patch_size=32" \
  --gin_bindings="Config.dilate=4" \
  --gin_bindings="Config.data_loss_type='on-the-go'"
  
python -m train \
  --gin_configs=configs/360_dino.gin \
  --gin_bindings="Config.data_dir='Datasets/on-the-go/corner'" \
  --gin_bindings="Config.checkpoint_dir='output/corner/run_1/checkpoints'" \
  --gin_bindings="Config.patch_size=32" \ 
  --gin_bindings="Config.dilate=4" \
  --gin_bindings="Config.data_loss_type='on-the-go'"
  
python -m train \
  --gin_configs=configs/360_dino.gin \
  --gin_bindings="Config.data_dir='Datasets/on-the-go/patio'" \
  --gin_bindings="Config.checkpoint_dir='output/patio/run_1/checkpoints'" \
  --gin_bindings="Config.patch_size=32" \
  --gin_bindings="Config.dilate=4" \
  --gin_bindings="Config.data_loss_type='on-the-go'" \
  --gin_bindings="Config.train_render_every = 5000" \
  --gin_bindings="Config.H = 1080" \ 
  --gin_bindings="Config.W = 1920" \ 
  --gin_bindings="Config.factor = 4" \
  --gin_bindings="Config.feat_rate = 2"

python -m train \
  --gin_configs=configs/360_dino.gin \
  --gin_bindings="Config.data_dir='Datasets/on-the-go/spot'" \
  --gin_bindings="Config.checkpoint_dir='output/spot/run_1/checkpoints'" \
  --gin_bindings="Config.patch_size=32" \
  --gin_bindings="Config.dilate=4" \
  --gin_bindings="Config.data_loss_type='on-the-go'"

python -m train \
  --gin_configs=configs/360_dino.gin \
  --gin_bindings="Config.data_dir='Datasets/on-the-go/patio_high'" \
  --gin_bindings="Config.checkpoint_dir='output/patio_high/run_1/checkpoints'" \
  --gin_bindings="Config.patch_size=32" \
  --gin_bindings="Config.dilate=4" \
  --gin_bindings="Config.data_loss_type='on-the-go'" 
```

</details>

and found that our `eval_metrics/psnr` was much worse than the paper's metrics:

  | Mountain | Fountain | Corner | Patio | Spot | Patio-High
-- | -- | -- | -- | -- | -- | --
onthego (paper) | 20.15 | 20.11 | 24.22 | 20.78 | 23.33 | 21.41
onthego (our env) | 18.34 | 15.59 | 20.82 | 16.71 | 16.32 | 14.59

In addition, we found that the fountain was missing in the rendered `fountain` model.

Do you have any suggestion to fix it and reproduce the paper's PSNR?

![Image](https://github.com/user-attachments/assets/d91f917e-d184-4df8-a153-b24d8e3a7761)

**Comment by rwn17** [comment]
Hi @Yosshi999, I will check it again in the coming weeks. When I released the code, I tested it in a new environment, and it worked fine. Some of the scene checkpoints are available at the following link: https://drive.google.com/file/d/1T8i05-jzauHIkg-iLYEwJIIngHSAu74t/view?usp=sharing

**Comment by rwn17** [comment]
<html><head></head><body><p>Hi @Yosshi999,</p>
<p>Thank you for your interest in our project.</p>
<p>I recently ran the instructions from scratch on a new server (at HKU) and suspect that the issue you’re encountering is due to the absence of <code>mogrify</code> on your system when executing the dataset script (<a href="https://github.com/cvg/nerf-on-the-go/blob/master/scripts/download_on-the-go.sh#L35">download_on-the-go.sh line 35</a>). Without <code>mogrify</code>, the downsampling process is not executed.</p>
<p>To resolve this, please install ImageMagick (which includes <code>mogrify</code>) by running:</p>
<pre><code class="language-bash">conda install -y -c conda-forge imagemagick
</code></pre>
<p>Please note that our solution is sensitive to the patch size relative to the full resolution; therefore, the results you obtain may differ if the patch size is not set precisely. For reference, I have trained two high-occlusion scenarios on the new server and observed slightly better PSNR compared to the paper:</p>

Scene | Spot | Patio-High
-- | -- | --
onthego (paper) | 23.33 | 21.41
onthego (ckpt) | 24.67 | 22.30


<p>I have uploaded the models for these high-occlusion scenes <a href="https://connecthkuhk-my.sharepoint.com/:u:/g/personal/weining_connect_hku_hk/EQE_y0vx241Nqge_jCwWWHcBCIWAsRKlTy2fwhFlResx9A?e=YkGIj6">here</a>. Next week, I will finish the experiments on all scenes and update the repository with the checkpoints and a revised README file.</p>
<p>If you have any further questions, please feel free to reach out.</p>
<p>Best regards,<br>
Weining

**Comment by Yosshi999** [comment]
It seems my images were correctly downsampled.
Could you show me the detailed environment like `pip freeze` ?
I suspect the version of the libraries or the GPU architectures.

Here is my freeze:

<details>
<summary>pip freeze</summary>

```
absl-py==2.1.0
asttokens==3.0.0
astunparse==1.6.3
beautifulsoup4==4.13.4
blinker==1.4
certifi==2025.1.31
charset-normalizer==3.4.1
chex==0.1.89
contourpy==1.3.2
cryptography==3.4.8
cycler==0.12.1
dbus-python==1.2.18
decorator==5.2.1
distro==1.7.0
distro-info==1.1+ubuntu0.2
dm_pix==0.4.4
etils==1.12.2
executing==2.2.0
filelock==3.18.0
flatbuffers==25.2.10
flax==0.10.6
fonttools==4.58.0
fsspec==2025.5.0
gast==0.6.0
gdown==5.2.0
gin-config==0.5.0
google-pasta==0.2.0
grpcio==1.71.0
h5py==3.13.0
httplib2==0.20.2
idna==3.10
importlib-metadata==4.6.4
importlib_resources==6.5.2
ipython==9.2.0
ipython_pygments_lexers==1.1.1
jax==0.4.29
jaxlib==0.4.29+cuda12.cudnn91
jedi==0.19.2
jeepney==0.7.1
Jinja2==3.1.6
keras==3.9.0
keyring==23.5.0
kiwisolver==1.4.8
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
libclang==18.1.1
lpips_jax==0.1.0
Markdown==3.7
markdown-it-py==3.0.0
MarkupSafe==3.0.2
matplotlib==3.8.4
matplotlib-inline==0.1.7
mdurl==0.1.2
mediapy==1.2.4
ml_dtypes==0.5.1
more-itertools==8.10.0
mpmath==1.3.0
msgpack==1.1.0
namex==0.0.8
natsort==8.4.0
nest-asyncio==1.6.0
networkx==3.4.2
numpy==2.1.3
nvidia-cublas-cu12==12.6.4.1
nvidia-cuda-cupti-cu12==12.6.80
nvidia-cuda-nvrtc-cu12==12.6.77
nvidia-cuda-runtime-cu12==12.6.77
nvidia-cudnn-cu12==9.5.1.17
nvidia-cufft-cu12==11.3.0.4
nvidia-cufile-cu12==1.11.1.6
nvidia-curand-cu12==10.3.7.77
nvidia-cusolver-cu12==11.7.1.2
nvidia-cusparse-cu12==12.5.4.2
nvidia-cusparselt-cu12==0.6.3
nvidia-nccl-cu12==2.26.2
nvidia-nvjitlink-cu12==12.6.85
nvidia-nvtx-cu12==12.6.77
oauthlib==3.2.0
opencv-python==4.11.0.86
opt_einsum==3.4.0
optax==0.2.4
optree==0.14.1
orbax-checkpoint==0.3.5
packaging==24.2
parso==0.8.4
pexpect==4.9.0
pillow==11.2.1
prompt_toolkit==3.0.51
protobuf==5.29.3
ptyprocess==0.7.0
pure_eval==0.2.3
pycolmap @ git+https://github.com/brandonyzhao/pycolmap.git@a2a5671b0f6ab641957dd4c5a78cabcf220c28ee
Pygments==2.19.1
PyGObject==3.42.1
PyJWT==2.3.0
pyparsing==2.4.7
PySocks==1.7.1
python-apt==2.4.0+ubuntu4
python-dateutil==2.9.0.post0
PyYAML==6.0.2
rawpy==0.25.0
requests==2.32.3
rich==13.9.4
scipy==1.15.3
SecretStorage==3.3.1
six==1.16.0
soupsieve==2.7
stack-data==0.6.3
sympy==1.14.0
tensorboard==2.19.0
tensorboard-data-server==0.7.2
tensorflow==2.19.0
tensorflow-io-gcs-filesystem==0.37.1
tensorstore==0.1.75
termcolor==2.5.0
toolz==1.0.0
torch==2.7.0
torchaudio==2.7.0
torchvision==0.22.0
tqdm==4.67.1
traitlets==5.14.3
treescope==0.1.9
triton==3.3.0
typing_extensions==4.12.2
unattended-upgrades==0.1
urllib3==2.3.0
wadllib==1.3.6
wcwidth==0.2.13
Werkzeug==3.1.3
wrapt==1.17.2
zipp==1.0.0
```

</details>

And here is the log of fountain

**true color 26**
![Image](https://github.com/user-attachments/assets/bf3374db-22f9-42b0-9541-0c6528149d17)

**uncertainty 26**
![Image](https://github.com/user-attachments/assets/d78225a8-a4ed-4fc7-941a-de966ccf0ff1)

**dino var**
<img width="405" alt="Image" src="https://github.com/user-attachments/assets/f7c73106-6d0e-4066-bca2-327208d754aa" />

**Comment by rwn17** [comment]
Hi @Yosshi999,

I tested the setup on a different server (4×L20) and ran it again—it still works as expected. For this project, I originally used 4×4090 and 1×A100. Now, I’ve tested it with 4×4090, 2×H800, and 4×L20, and it also works out of the box. You can find the [environment settings](https://connecthkuhk-my.sharepoint.com/:t:/g/personal/weining_connect_hku_hk/ERaKenUc_VxEkVL9gwEEQRcBOAWsYyGmsmi3aZSjDqnwkg?e=88sPnK) I used here.

Additionally, I re-ran the fountain scene and recorded the training loss for your reference. I’ve uploaded the [TensorBoard logs](https://connecthkuhk-my.sharepoint.com/:u:/g/personal/weining_connect_hku_hk/EXngcKHtFLBEmNp_vSXwdWgBYF9RmtfYCTDORpmRJFkddw?e=93kwCn) and the [processed dataset](https://connecthkuhk-my.sharepoint.com/:u:/g/personal/weining_connect_hku_hk/ETsQqng4t1BOsSHGDNVXoEIBgtteGEy6wDzV1i_--yLLxQ?e=avkndB) for your convenience. I hope they can help.

<img width="1478" alt="Image" src="https://github.com/user-attachments/assets/ae396530-b1f8-4adb-9ae2-a93a1e5ed486" />

<img width="391" alt="Image" src="https://github.com/user-attachments/assets/5d5a2525-a355-4e91-bc25-1df571cbc091" />

<img width="416" alt="Image" src="https://github.com/user-attachments/assets/6e59b04f-b6d4-491e-9fc0-8324ac74e50d" />

I’m not sure what might be causing issues with your reproduction, but I suggest tuning the `patch_size` and `dilation_ratio` if it still doesn't work. We discuss the influence of these hyperparameters in our paper.

Best regards,  
Weining

**Comment by Yosshi999** [comment]
Thank you for your investigation.
I tried your pip environment and the fountain dataset linked above but the issue wasn't solved, but it looks better when I increase `reg_mult` from 0.5 to 2.5.
I'm going to run all experiments with this parameter.

<img width="924" alt="Image" src="https://github.com/user-attachments/assets/712aa574-40dd-490b-adf0-4af9cf625195" />

**Comment by Yosshi999** [comment]
I forgot to run the unittest on my environment.
I found some cases are failed, but the error looks small enough.

```
.
----------------------------------------------------------------------
Ran 1 test in 5.672s

OK
...................................F....................
======================================================================
FAIL: test_sample_intervals_unbiased_random_bounded (tests.stepfun_test.StepFunTest)
tests.stepfun_test.StepFunTest.test_sample_intervals_unbiased_random_bounded
test_sample_intervals_unbiased_random_bounded(True, True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/workspace/lib/python3.12/site-packages/absl/testing/parameterized.py", line 323, in bound_param_test
    return test_method(self, *testcase_params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/src/tests/stepfun_test.py", line 569, in test_sample_intervals_unbiased
    np.testing.assert_allclose(jnp.median(t_sampled[:, 0]), -0.5, atol=1e-4)
  File "/workspace/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 1691, in assert_allclose
    assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
  File "/usr/lib/python3.12/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/workspace/lib/python3.12/site-packages/numpy/testing/_private/utils.py", line 889, in assert_array_compare
    raise AssertionError(msg)
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0.0001

Mismatched elements: 1 / 1 (100%)
Max absolute difference among violations: 0.00020468
Max relative difference among violations: 0.00040936
 ACTUAL: array(-0.499795, dtype=float32)
 DESIRED: array(-0.5)

----------------------------------------------------------------------
Ran 56 tests in 89.144s

FAILED (failures=1)
Mean Error = 0.08684495836496353, Tolerance = 0.1
Mean Error = 0.08817846328020096, Tolerance = 0.1
.....................
----------------------------------------------------------------------
Ran 21 tests in 31.957s

OK
PE of degree 5 has a maximum error of 2.5369226932525635e-06
PE of degree 10 has a maximum error of 6.4849853515625e-05
PE of degree 15 has a maximum error of 0.002378210425376892
PE of degree 20 has a maximum error of 0.11622805148363113
PE of degree 25 has a maximum error of 1.999955415725708
PE of degree 30 has a maximum error of 1.9999704360961914
....../workspace/src/internal/math.py:28: RuntimeWarning: overflow encountered in cast
  return fn(jnp.where(jnp.abs(x) < t, x, x % t))
/workspace/lib/python3.12/site-packages/jax/_src/numpy/lax_numpy.py:2850: RuntimeWarning: overflow encountered in cast
  return util._where(condition, x, y)
.
----------------------------------------------------------------------
Ran 7 tests in 7.388s

OK
```
